spring.application.name=metro-ticket-booking

# MySQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/metro
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update


# JWT Configuration
secretJwtString=24dbcf24ec28478a33de6d14eb3c09596baeb2f7a805f61d54d76b93eb48f7c7
